### ISSUE TITLE
airline theme farout is not found

### ISSUE THREAD

**Issue by ddemidov** [fcpg/vim-farout#1]
`:AirlineTheme farout` results in `The specified theme cannot be found` error, although tab completion seems to know about `farout` (`:ArlineTheme far<Tab>` gives `farout`).

The `fahrenheit` airline theme works though, and the plugin structures are identical, so not sure what is going on. The vim version is 8.0.

**Comment by fcpg** [comment]
Right, there was a typo in the airline theme. Thanks for reporting it.
