### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [fcpg/vim-farout#6]
I want to make a port of this color scheme, but there is no license in this repository.
Maybe [Unlicense](https://unlicense.org/)?

**Comment by ghost** [comment]
Sorry, I did not read the README file. Closed.

**Comment by fcpg** [comment]
Hello!
There's a link in the Readme file to https://creativecommons.org/licenses/by-sa/4.0/
Basically do what you want, as long as you give me credit (ie. link to this repo) and use the same license as well.

Edit: you've seen it as I was writing :)
